const translation = {
    es: {
        "titulo_pagina": "COACHING SL | Iniciar Sesión",
        "inicio": "Inicio",
        "como_trabajar": "Cómo Trabajar",
        "contacto": "Puesta en contacto",
        "especialistas": "Especialistas",
        "calendario": "Calendario",
        "espanol": "Español",
        "catalan": "Catalán",
        "ingles": "Inglés",
        "frances": "Francés",
        "italiano": "Italiano",
        "euskera": "Euskera",
        "gallego": "Gallego",
        "sueco": "Sueco",
        "iniciar_sesion": "Iniciar Sesión",
        "registrar": "Registrar",
        "iniciar_sesion_titulo": "Iniciar Sesión",
        "correo_placeholder": "Introduce tu correo",
        "contrasena_placeholder": "Introduce tu contraseña",
        "boton_iniciar_sesion": "Iniciar Sesión",
        "registro_titulo": "Registro",
        "dni_placeholder": "Introduce tu DNI",
        "telefono_placeholder": "Introduce tu telefono",
        "nombre_placeholder": "Introduce tu nombre",
        "apellidos_placeholder": "Introduce tus apellidos",
        "fecha_nacimiento_placeholder": "Introduce tu fecha de nacimiento",
        "via_placeholder": "Introduce tipo de vía de su calle",
        "calle_placeholder": "Introduce el nombre de su calle",
        "numero_placeholder": "Introduce el numero de su calle",
        "boton_registrar": "Registrarse"
    },
    ca: {
        "titulo_pagina": "COACHING SL | Iniciar Sessió",
        "inicio": "Inici",
        "como_trabajar": "Com Treballar",
        "contacto": "Contacte",
        "especialistas": "Especialistes",
        "calendario": "Calendari",
        "espanol": "Espanyol",
        "catalan": "Català",
        "ingles": "Anglès",
        "frances": "Francès",
        "italiano": "Italià",
        "euskera": "Euskara",
        "gallego": "Gallec",
        "sueco": "Suec",
        "iniciar_sesion": "Iniciar Sessió",
        "registrar": "Registrar",
        "iniciar_sesion_titulo": "Iniciar Sessió",
        "correo_placeholder": "Introdueix el teu correu",
        "contrasena_placeholder": "Introdueix la teva contrasenya",
        "boton_iniciar_sesion": "Iniciar Sessió",
        "registro_titulo": "Registre",
        "dni_placeholder": "Introdueix el teu DNI",
        "telefono_placeholder": "Introdueix el teu telèfon",
        "nombre_placeholder": "Introdueix el teu nom",
        "apellidos_placeholder": "Introdueix els teus cognoms",
        "fecha_nacimiento_placeholder": "Introdueix la teva data de naixement",
        "via_placeholder": "Introdueix tipus de via del teu carrer",
        "calle_placeholder": "Introdueix el nom del teu carrer",
        "numero_placeholder": "Introdueix el número del teu carrer",
        "boton_registrar": "Registrar-se"
    },
    en: {
        "titulo_pagina": "COACHING SL | Log In",
        "inicio": "Home",
        "como_trabajar": "How it Works",
        "contacto": "Contact",
        "especialistas": "Specialists",
        "calendario": "Calendar",
        "espanol": "Spanish",
        "catalan": "Catalan",
        "ingles": "English",
        "frances": "French",
        "italiano": "Italian",
        "euskera": "Basque",
        "gallego": "Galician",
        "sueco": "Swedish",
        "iniciar_sesion": "Log In",
        "registrar": "Register",
        "iniciar_sesion_titulo": "Log In",
        "correo_placeholder": "Enter your email",
        "contrasena_placeholder": "Enter your password",
        "boton_iniciar_sesion": "Log In",
        "registro_titulo": "Register",
        "dni_placeholder": "Enter your ID",
        "telefono_placeholder": "Enter your phone number",
        "nombre_placeholder": "Enter your name",
        "apellidos_placeholder": "Enter your last name",
        "fecha_nacimiento_placeholder": "Enter your birth date",
        "via_placeholder": "Enter street type",
        "calle_placeholder": "Enter the name of your street",
        "numero_placeholder": "Enter your street number",
        "boton_registrar": "Register"
    },
    fr: {
        "titulo_pagina": "COACHING SL | Se connecter",
        "inicio": "Accueil",
        "como_trabajar": "Comment ça marche",
        "contacto": "Contact",
        "especialistas": "Spécialistes",
        "calendario": "Calendrier",
        "espanol": "Espagnol",
        "catalan": "Catalan",
        "ingles": "Anglais",
        "frances": "Français",
        "italiano": "Italien",
        "euskera": "Basque",
        "gallego": "Galicien",
        "sueco": "Suédois",
        "iniciar_sesion": "Se connecter",
        "registrar": "S'inscrire",
        "iniciar_sesion_titulo": "Se connecter",
        "correo_placeholder": "Entrez votre email",
        "contrasena_placeholder": "Entrez votre mot de passe",
        "boton_iniciar_sesion": "Se connecter",
        "registro_titulo": "S'inscrire",
        "dni_placeholder": "Entrez votre ID",
        "telefono_placeholder": "Entrez votre numéro de téléphone",
        "nombre_placeholder": "Entrez votre nom",
        "apellidos_placeholder": "Entrez votre prénom",
        "fecha_nacimiento_placeholder": "Entrez votre date de naissance",
        "via_placeholder": "Entrez le type de rue",
        "calle_placeholder": "Entrez le nom de votre rue",
        "numero_placeholder": "Entrez le numéro de votre rue",
        "boton_registrar": "S'inscrire"
    },
    it: {
        "titulo_pagina": "COACHING SL | Accedi",
        "inicio": "Home",
        "como_trabajar": "Come funziona",
        "contacto": "Contatti",
        "especialistas": "Specialisti",
        "calendario": "Calendario",
        "espanol": "Spagnolo",
        "catalan": "Catalano",
        "ingles": "Inglese",
        "frances": "Francese",
        "italiano": "Italiano",
        "euskera": "Basco",
        "gallego": "Galiziano",
        "sueco": "Svedese",
        "iniciar_sesion": "Accedi",
        "registrar": "Registrati",
        "iniciar_sesion_titulo": "Accedi",
        "correo_placeholder": "Inserisci la tua email",
        "contrasena_placeholder": "Inserisci la tua password",
        "boton_iniciar_sesion": "Accedi",
        "registro_titulo": "Registrazione",
        "dni_placeholder": "Inserisci il tuo ID",
        "telefono_placeholder": "Inserisci il tuo numero di telefono",
        "nombre_placeholder": "Inserisci il tuo nome",
        "apellidos_placeholder": "Inserisci il tuo cognome",
        "fecha_nacimiento_placeholder": "Inserisci la tua data di nascita",
        "via_placeholder": "Inserisci il tipo di via",
        "calle_placeholder": "Inserisci il nome della tua via",
        "numero_placeholder": "Inserisci il numero della tua via",
        "boton_registrar": "Registrati"
    },
    eu: {
        "titulo_pagina": "COACHING SL | Saioa hasi",
        "inicio": "Hasiera",
        "como_trabajar": "Nola Funtzionatzen Duen",
        "contacto": "Harremanetan",
        "especialistas": "Adituak",
        "calendario": "Egutegia",
        "espanol": "Espainiarra",
        "catalan": "Katalana",
        "ingles": "Ingelesa",
        "frances": "Frantsesa",
        "italiano": "Italia",
        "euskera": "Euskara",
        "gallego": "Gallego",
        "sueco": "Suediarra",
        "iniciar_sesion": "Saioa hasi",
        "registrar": "Erregistroa",
        "iniciar_sesion_titulo": "Saioa hasi",
        "correo_placeholder": "Idatzi zure posta",
        "contrasena_placeholder": "Idatzi zure pasahitza",
        "boton_iniciar_sesion": "Saioa hasi",
        "registro_titulo": "Erregistroa",
        "dni_placeholder": "Idatzi zure NAN",
        "telefono_placeholder": "Idatzi zure telefonoa",
        "nombre_placeholder": "Idatzi zure izena",
        "apellidos_placeholder": "Idatzi zure abizenak",
        "fecha_nacimiento_placeholder": "Idatzi zure jaiotze data",
        "via_placeholder": "Idatzi kaleko bide mota",
        "calle_placeholder": "Idatzi zure kalearen izena",
        "numero_placeholder": "Idatzi zure kaleko zenbakia",
        "boton_registrar": "Erregistroa"
    },
    gl: {
        titulo_pagina: "COACHING SL | Iniciar Sesión",
        inicio: "Inicio",
        como_trabajar: "Como Traballar",
        contacto: "Póñase en contacto",
        especialistas: "Especialistas",
        calendario: "Calendario",
        iniciar_sesion: "Iniciar Sesión",
        registrar: "Rexistrarse",
        iniciar_sesion_titulo: "Iniciar Sesión",
        correo_placeholder: "Introduce o teu correo",
        contrasena_placeholder: "Introduce a túa contrasinala",
        boton_iniciar_sesion: "Iniciar Sesión",
        registro_titulo: "Rexistro",
        dni_placeholder: "Introduce o teu DNI",
        telefono_placeholder: "Introduce o teu teléfono",
        nombre_placeholder: "Introduce o teu nome",
        apellidos_placeholder: "Introduce os teus apelidos",
        fecha_nacimiento_placeholder: "Introduce a túa data de nacemento",
        via_placeholder: "Introduce tipo de vía da túa rúa",
        calle_placeholder: "Introduce o nome da túa rúa",
        numero_placeholder: "Introduce o número da túa rúa",
        boton_registrar: "Rexistrarse"
    },
    su: {
        titulo_pagina: "COACHING SL | Logga In",
        inicio: "Hem",
        como_trabajar: "Hur Det Fungerar",
        contacto: "Kontakta Oss",
        especialistas: "Specialister",
        calendario: "Kalender",
        iniciar_sesion: "Logga In",
        registrar: "Registrera",
        iniciar_sesion_titulo: "Logga In",
        correo_placeholder: "Ange din e-postadress",
        contrasena_placeholder: "Ange ditt lösenord",
        boton_iniciar_sesion: "Logga In",
        registro_titulo: "Registrera",
        dni_placeholder: "Ange ditt ID",
        telefono_placeholder: "Ange ditt telefonnummer",
        nombre_placeholder: "Ange ditt namn",
        apellidos_placeholder: "Ange ditt efternamn",
        fecha_nacimiento_placeholder: "Ange ditt födelsedatum",
        via_placeholder: "Ange din gatutyp",
        calle_placeholder: "Ange ditt gatunamn",
        numero_placeholder: "Ange ditt gatunumero",
        boton_registrar: "Registrera"
    }
}
// Idioma predeterminado
let currentLanguage = 'es'; // Valor predeterminado: español

// Función para cargar las traducciones y actualizar el contenido de la página
// Función para cargar las traducciones y actualizar el contenido de la página
function loadLanguage(language) {
    console.log("Cargando idioma: ", language); // Agregar log aquí
    // Verificar si el idioma existe en el objeto de traducciones
    if (translation[language]) {
        const translatableElements = document.querySelectorAll('[data-translate]');
        translatableElements.forEach(element => {
            const key = element.getAttribute('data-translate');
            const translatedText = translation[language][key];
            if (translatedText) {
                // Si el elemento es un input, actualizar el placeholder
                if (element.tagName.toLowerCase() === 'input') {
                    element.setAttribute('placeholder', translatedText);
                } else {
                    element.textContent = translatedText;
                }
            }
        });
    }
}

// Event listener para cambiar el idioma
document.getElementById('lenguage').addEventListener('change', function (event) {
    currentLanguage = event.target.value; // Actualizar el idioma seleccionado
    loadLanguage(currentLanguage); // Aplicar las traducciones
});

// Cargar el idioma predeterminado al iniciar
loadLanguage(currentLanguage);
